### ISSUE TITLE
Some questions about inp_rays

### ISSUE THREAD

**Issue by Arcxml** [chenhonghua/MVIP-NeRF#10]
<img width="890" alt="image" src="https://github.com/user-attachments/assets/f47bef39-6972-4fed-9ee3-9df500c99354">
hello, I want to ask one more question. In this picture, you save the inpainted depth in your code, but in the following code, I don't see any steps to filter the content within the mask.
Am I missing some code? I think the depth in the mask should be filtered.

**Comment by chenhonghua** [comment]
Hi, rays_inp is filtered by masks. 

Please see the code in Line 713. You may need to update the code since I missed this line in the previous version.

**Comment by MnKnight1** [comment]
rays_rgb.shape and labels.shape: (60, 3, 567, 1008, 3) (60, 3, 567, 1008, 1) (60, 567, 1008, 3) (60, 567, 1008) (60, 3, 4)
######################## (60, 567, 1008, 3) (60, 2, 567, 1008, 3) (60, 3, 567, 1008, 3) (60, 3, 567, 1008, 1)
get depth rays
rays_weights mean: 0.6700967097351238
rays_weights std: 0.3286558790822371
rays_weights max: 1.9999993052881542
rays_weights min: 0.001487879279390992
rays_depth.shape: (646702, 4, 3)
shuffle depth rays
done
Traceback (most recent call last):
  File "/media/data/litaiqing/anaconda3/envs/mv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/data/litaiqing/anaconda3/envs/mv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/litaiqing/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/litaiqing/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/litaiqing/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/litaiqing/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/litaiqing/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/litaiqing/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/media/data/litaiqing/code/MVIP-NeRF/DS_NeRF/run.py", line 1980, in <module>
    train()
  File "/media/data/litaiqing/code/MVIP-NeRF/DS_NeRF/run.py", line 713, in train
    rays_inp = rays_inp[rays_rgb[:, :, 3] == 0].reshape(-1, 3, 4)       ################# modified #####################
IndexError: boolean index did not match indexed array along dimension 0; dimension is 34292160 but corresponding boolean dimension is 2082015
how to solve this?

**Comment by MnKnight1** [comment]
```
        if not args.prepare:                                               ################# modified #####################
            mask=(rays_rgb[:, :, 3] == 1)
            rays_rgb = rays_rgb[mask].reshape(-1, 3, 4)  ################# modified #####################
            rays_inp = rays_inp[mask].reshape(-1, 3, 4)       ################# modified #####################
```
I have changed the code in Line 713 like this, is this ture?
